# Generated by Django 4.2 on 2025-10-12 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_desc',
            field=models.CharField(max_length=100),
        ),
    ]
