# Generated by Django 4.2 on 2025-10-14 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://orders.goodthymes.ca/assets/img/goodthymes/default-menu-image-placeholder.png', max_length=500),
        ),
    ]
