# Generated by Django 4.2 on 2025-10-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_item_item_image_item_image_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='image_item',
            new_name='item_image',
        ),
    ]
